application: traic-coer
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|GIF))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|GIF))
  
- url: /(.*\.(cur))
  static_files: \1
  upload: (.*\.(cur))

- url: .*
  script: main.py
